server:
  port: 8081
spring:
  security:
    user:
      name: admin
      password: admin
  mvc:
    throw-exception-if-no-handler-found: false
    static-path-pattern: /static/tmp/**
  datasource:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
    password: ''
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./h2db/mall;MODE=MYSQL
    username: sa
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: false
  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    show-sql: true
    open-in-view: true
  jackson:
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null
    date-format: yyyy/MM/dd HH:mm:ss
  thymeleaf:
    cache: true
logging:
  level:
    root: info
application:
  cert-file-name: cert-20210125.p12
  cert-pwd: bp
