server:
  port: 8081
spring:
  mvc:
    throw-exception-if-no-handler-found: false
  datasource:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
    password: ''
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./h2db/mall;MODE=MYSQL
    username: sa
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    show-sql: true
    open-in-view: true
  jackson:
    default-property-inclusion: non_null
